apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tfm-deployer-binding
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: tfm-deployer
    namespace: prod
roleRef:
  kind: Role
  name: tfm-deployer-role
  apiGroup: rbac.authorization.k8s.io
