{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tfm-app.fullname" . }}-np
spec:
  podSelector:
    matchLabels:
      {{- include "tfm-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.networkPolicy.allowIngressFromSameNamespace }}
    - from:
        - podSelector: {}
    {{- else }}
    - from: []
    {{- end }}
{{- end }}
