---
- name: Actualizar repositorios
  apt:
    update_cache: yes

- name: Instalar paquetes esenciales
  apt:
    name:
      - curl
      - vim
      - git
      - unzip
      - htop
      - net-tools
    state: present

- name: Configurar mensaje MOTD
  template:
    src: motd.j2
    dest: /etc/motd

- name: Desactivar SWAP para Kubernetes
  command: swapoff -a
  when: "'k8s' in group_names"

- name: Eliminar swap de fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*(.*swap.*)$'
    replace: '# \1'
  when: "'k8s' in group_names"
