# Configuración de despliegue para el servicio principal (Monolito)
# Contexto: Gestiona el tráfico general de la aplicación excepto módulos desagregados.

# Identificador inmutable para descubrimiento de servicio
fullnameOverride: "petclinic-monolith"

# Alta disponibilidad: Configuración base de 2 réplicas (Paridad con entorno Legacy)
replicaCount: 2

image:
  repository: "jolrojasbodev/spring-petclinic"
  pullPolicy: IfNotPresent

# Configuración de red interna
# La exposición externa se delega exclusivamente al recurso Ingress unificado
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Desactivación de Ingress por defecto del Chart para evitar conflictos de enrutamiento
ingress:
  enabled: false

# Inyección de dependencias de persistencia
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "mysql"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://mysql-db:3306/petclinic"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: password

# Sondas de Salud (Health Probes)
# Tiempos extendidos para mitigar latencia de inicialización de JVM/Hibernate
readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 45
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 80
  periodSeconds: 15

# Límites de recursos (QoS: Burstable)
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi