# Configuración de despliegue para el microservicio desagregado "Vets"
# Estrategia: Strangler Fig Pattern

# Identificador de servicio para reglas de enrutamiento Ingress
fullnameOverride: "petclinic-vets"

# Dimensionamiento específico para el módulo de veterinarios
replicaCount: 1

image:
  repository: "jolrojasbodev/spring-petclinic"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Gestión de tráfico delegada al Ingress global
ingress:
  enabled: false

# Configuración de persistencia compartida
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "mysql"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://mysql-db:3306/petclinic"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: password

# Configuración de estabilidad de runtime
readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 45
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 80
  periodSeconds: 15

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi